# Travis-CI Build for Cronos
# see travis-ci.org for details

sudo: required
dist: trusty
dotnet: 1.0.1

language: cpp

os: 
  - linux
  - osx
  
env:  
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1

# Run the build script
script:
    travis_retry dotnet restore Cronos.sln --disable-parallel;
    dotnet test tests/Cronos.Tests/Cronos.Tests.csproj -c:Release -f:netcoreapp1.0;
  
  

