# Travis-CI Build for Cronos
# see travis-ci.org for details

sudo: required
dist: trusty

language: cpp

matrix:
  include:
    - os: linux
    - os: osx

before_install:  
  - if test "$TRAVIS_OS_NAME" == "osx"; 
    then 
        brew update;
        brew install openssl --force;
        mkdir -p /usr/local/lib;
        ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/;
        ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/;
        sudo curl -o \"/tmp/dotnet.pkg\" -fL https://go.microsoft.com/fwlink/?linkid=841692;
        sudo installer -package "/tmp/dotnet.pkg" -target "/";
        eval $(/usr/libexec/path_helper -s);
    else
        sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list';
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893;
        sudo apt-get update;
        sudo apt-get install dotnet-dev-1.0.0-rc4-004771; 
    fi

# Run the build script
script:
    travis_retry dotnet restore Cronos.sln --disable-parallel;
    dotnet msbuild tests/Cronos.Tests/Cronos.Tests.csproj /p:DefineConstants=IANA_SUPPORTED /p:Configuration=Release /p:TargetFramework=netcoreapp1.0;
    dotnet test tests/Cronos.Tests/Cronos.Tests.csproj --no-build -c:Release -f:netcoreapp1.0 -verbosity:d;
  

