# AppVeyor CI build file, https://ci.appveyor.com/project/odinserj/cronos

os: Visual Studio 2017 RC

# Don't edit manually! Use `.\build.ps1 -ScriptArgs '--newVersion="*.*.*"'` command instead!
version: 0.2.0-build-0{build}

branches:
  only:
    - master
    - dev

pull_requests:
  do_not_increment_build_number: true

shallow_clone: true

#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - powershell .\build.ps1 -Target CI
  
#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: 'build\*.nupkg'
  - path: 'build\*.zip'

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

deploy:
  - provider: GitHub
    auth_token:
      secure: Hw+eMEw//BNM8ZZSQidchwbrj25XFKykj+NdQKXtXWEsHKZdXTWRZjfDjK6UZLxU
    artifact: /.*\.zip/
    draft: true
    on:
      appveyor_repo_tag: true

  - provider: NuGet
    api_key: 
      secure: P7SfXBeFQixVqdEFlyFtRb39IytB+/RijG46obop/pv64uBk7uEba4p4oNZOvHde
    on:
      appveyor_repo_tag: true